Winmed/Models/Empresa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Winmed.Models
{
    public class Empresa
    {
        public int ID { get; set; }
        
        [Required]
        public string RazaoSocial { get; set; }

        [Required]
        public string NomeFantasia { get; set; }
        
        [Required]
        public string Endereco { get; set; }

        [RegularExpression(@"^[0-9]*$", ErrorMessage = "O Numero deve ser preenchido em um formato válido")]
        [Required]
        public string Numero { get; set; }

        public string Complemento { get; set; }
        
        [Required]
        public string Bairro { get; set; }

        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "O Email deve ser preenchido em um formato válido")]
        [Required]
        public string Email { get; set; }

        [Required]
        public string CNPJ { get; set; }
    }
}

Winmed/Models/EmpresaContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Winmed.Models
{
    public class EmpresaContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public EmpresaContext() : base("name=EmpresaContext")
        {
        }

        public System.Data.Entity.DbSet<Winmed.Models.Empresa> Empresas { get; set; }
    }
}

Winmed/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Winmed.Models
{
    public class Usuario
    {        
            public int ID { get; set; }

            [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$", ErrorMessage = "O Nome deve ser preenchido em um formato válido")]
            [Required]
            public string Nome{ get; set; }

            [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$", ErrorMessage = "O Sobrenome deve ser preenchido em um formato válido")]
            [Required]
            public string Sobrenome { get; set; }

            [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "O Email deve ser preenchido em um formato válido")]
            [Required]
            public string Email { get; set; }

            [RegularExpression(@"([0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})", ErrorMessage = "O CPF deve ser preenchido em um formato válido.")]
            [Required]
            public string CPF { get; set; }
    }
}

Winmed/Models/UsuarioContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Winmed.Models
{
    public class UsuarioContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public UsuarioContext() : base("name=UsuarioContext")
        {
        }

        public System.Data.Entity.DbSet<Winmed.Models.Usuario> Usuarios { get; set; }
    }
}

Winmed/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Winmed.Models;

namespace Winmed.Controllers
{
    public class EmpresasController : Controller
    {
        private EmpresaContext db = new EmpresaContext();

        // GET: Empresas
        public ActionResult Index()
        {
            return PartialView(db.Empresas.ToList());
        }

        // GET: Empresas/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Empresas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RazaoSocial,NomeFantasia,Endereco,Numero,Complemento,Bairro,Email,CNPJ")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Empresas.Add(empresa);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return Json(new { success = false });
        }        

        // GET: Empresas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresas.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // POST: Empresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empresa empresa = db.Empresas.Find(id);
            db.Empresas.Remove(empresa);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Winmed/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Winmed.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Winmed/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Winmed.Models;

namespace Winmed.Controllers
{
    public class UsuariosController : Controller
    {
        private UsuarioContext db = new UsuarioContext();

        // GET: Usuarios
        public ActionResult Index()
        {
            return PartialView(db.Usuarios.ToList());
        }


        // GET: Usuarios/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Sobrenome,Email,CPF")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return Json(new { success = true });
            }            

            return Json(new { success = false });
        }        

        // GET: Usuarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Winmed/Views/Empresas/Create.cshtml
@model Winmed.Models.Empresa

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "signupform" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Empresa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazaoSocial, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.RazaoSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeFantasia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeFantasia, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.NomeFantasia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.CNPJ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="@Url.Content("~/node_modules/jquery-mask-plugin/dist/jquery.mask.js")"></script>
<script src="@Url.Content("~/node_modules/jquery-validation/dist/jquery.validate.js")"></script>
<script src="@Url.Content("~/node_modules/bootstrap-table/dist/bootstrap-table.js")"></script>
<script>
    $("#signupform").on('submit', function (e) {

        e.preventDefault();
        var dataToPost = $(this).serialize();
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create")',
            data: dataToPost,
            dataType: "json",
            success: function (data) {
                if (data.success) {
                    alert("A Empresa foi criada com sucesso!");
                    $('#content-container').load('@Url.Action("Index","Empresas")');
                }
                else {
                    alert("Erro ao criar empresa");
                }
            },
            error: function () {
                alert("Erro ao criar empresa");
            }
        });
    })

    function init() {
        $("#CNPJ").mask("99.999.999/9999-99", { reverse: true, placeholder: "99.999.999/9999-99"});
    };

    $(function () { // DOM carregado
        init();
    });
</script>

Winmed/Views/Empresas/Delete.cshtml
@model Winmed.Models.Empresa

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Tem certeza que deseja deletar essa empresa?</h3>
    <div>
        <h4>Empresa</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.RazaoSocial)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.RazaoSocial)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.NomeFantasia)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NomeFantasia)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Endereco)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Endereco)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Numero)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Numero)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Complemento)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Complemento)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Bairro)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Bairro)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CNPJ)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CNPJ)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        }
    </div>
</body>
</html>

Winmed/Views/Empresas/Index.cshtml
@model IEnumerable<Winmed.Models.Empresa>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}
<link href="@Url.Content("~/Content/Empresa/CSS/empresa.min.css")" rel="stylesheet" />
<link href="@Url.Content("~/node_modules/bootstrap-table/src/bootstrap-table.css")" rel="stylesheet" />
<div class="container-user">
    <h4>Lista de usuários</h4>
    <table id="table"
           data-toggle="table"
           data-search="true"
           data-filter-control="true"
           data-show-export="true"
           data-click-to-select="false"
           data-toolbar="#toolbar">
        <thead>
            <tr>
                <th data-field="ID" data-filter-control="input" data-sortable="true">
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th data-field="RazaoSocial" data-filter-control="input" data-sortable="true">
                    @Html.DisplayNameFor(model => model.RazaoSocial)
                </th>
                <th data-field="NomeFantasia" data-filter-control="input" data-sortable="true">
                    @Html.DisplayNameFor(model => model.NomeFantasia)
                </th>
                <th data-field="Email" data-filter-control="input" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th data-field="Endereco" data-filter-control="select" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Endereco)
                </th>
                <th data-field="Numero" data-filter-control="select" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Numero)
                </th>
                <th data-field="Complemento" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Complemento)
                </th>
                <th data-field="Bairro" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Bairro)
                </th>
                <th data-field="CNPJ" data-sortable="true">
                    @Html.DisplayNameFor(model => model.CNPJ)
                </th>
                <th data-field="Delete" data-sortable="true">
                    Remover
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td id="id">
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RazaoSocial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeFantasia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Endereco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Numero)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Complemento)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Bairro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CNPJ)
                </td>

                <td>
                    <button class='btn btn-danger remover-empresa' id="lista_empresas">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                </td>
            </tr>
            }
        </tbody>
    </table>

    <script>
        $(document.body).on('click', '.remover-empresa', function () {
            if (confirm("Tem certeza que deseja remover a empresa?")) {

                var id = $(this).closest('tr').find('#id').html();
                var form = $('#__AjaxAntiForgeryForm');
                var token = $('input[name="__RequestVerificationToken"]', form).val();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete")',
                    data: {
                        __RequestVerificationToken: token,
                        id: id
                    },
                    dataType: "json",
                    success: function () {
                        alert('Empresa removida com sucesso!');
                        $('#content-container').load('@Url.Action("Index","Empresas")');
                    },
                    error: function () {
                        alert("Erro ao remover empresa");
                    }
                });
            }
        })

    </script>
    <script src="@Url.Content("~/node_modules/bootstrap-table/dist/bootstrap-table.js")"></script>
    <script src="@Url.Content("~/node_modules/bootstrap-table/dist/locale/bootstrap-table-pt-BR.js")"></script>

Winmed/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section css {
    <link href="@Url.Content("~/Content/Home/CSS/homepage.min.css")" rel="stylesheet" />
}

    <div id="container">
        <div class="box1">
            <div class='card'>
                <div class='card-img-top'>
                    <img alt='' class='img-fluid' src="@Url.Content("~/Content/Home/Images/usuariolist.png")" />
                </div>
                <div class='card-block'>
                    <h4 class='card-title'>Lista de usuários</h4>
                    <button class='btn btn-primary' id="lista_usuarios">
                        <span class="glyphicon glyphicon-list"></span>
                    </button>
                </div>
            </div>
        </div>
        <div class="box2">
            <div class='card'>
                <div class='card-img-top'>
                    <img alt='' class='img-fluid' src="@Url.Content("~/Content/Home/Images/empresalist.png")" />
                </div>
                <div class='card-block'>
                    <h4 class='card-title'>Lista de empresas</h4>
                    <button class='btn btn-primary' id="lista_empresas">
                        <span class="glyphicon glyphicon-list"></span>
                    </button>
                </div>
            </div>
        </div>
        <div class="box3">
            <div class='card'>
                <div class='card-img-top'>
                    <img alt='' class='img-fluid' src="@Url.Content("~/Content/Home/Images/usuario.png")" />
                </div>
                <div class='card-block'>
                    <h4 class='card-title'>Cadastro de usuário</h4>
                    <button class='btn btn-primary' id="cadastro_usuario">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </button>
                </div>
            </div>
        </div>
        <div class="box4">
            <div class='card'>
                <div class='card-img-top'>
                    <img alt='' class='img-fluid' src="@Url.Content("~/Content/Home/Images/empresa.png")" />
                </div>
                <div class='card-block'>
                    <h4 class='card-title'>Cadastro de empresa</h4>
                    <button class='btn btn-primary' id="cadastro_empresa">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </button>
                </div>
            </div>
        </div>
        <span class="stretch">
        </span>
</div>
<div id="content-container">

</div>
<script>
    $('#lista_usuarios').click(function () {
        $('#content-container').load('@Url.Action("Index","Usuarios")');
    });
    $('#cadastro_usuario').click(function () {
        $('#content-container').load('@Url.Action("Create","Usuarios")');
    });
        $('#lista_empresas').click(function () {
        $('#content-container').load('@Url.Action("Index","Empresas")');
    });
    $('#cadastro_empresa').click(function () {
        $('#content-container').load('@Url.Action("Create", "Empresas")');
    });
</script>

Winmed/Views/Usuarios/Create.cshtml
@model Winmed.Models.Usuario
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "signupform" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cadastro de Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Nome Exemplo" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Sobrenome exemplo" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "seuemail@dominio.com" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" id="cadastrar_usuario" />
            </div>
        </div>
    </div>
}


<script src="@Url.Content("~/node_modules/jquery-mask-plugin/dist/jquery.mask.js")"></script>
<script src="@Url.Content("~/node_modules/jquery-validation/dist/jquery.validate.js")"></script>
<script src="@Url.Content("~/node_modules/bootstrap-table/dist/bootstrap-table.js")"></script>
<script>
    $("#signupform").on('submit', function (e) {

        e.preventDefault();
        var dataToPost = $(this).serialize();
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create")',
            data: dataToPost,
            dataType: "json",
            success: function (data) {
                if (data.success) {
                    alert("O usuário foi criado com sucesso!");
                    $('#content-container').load('@Url.Action("Index","Usuarios")');
                }
                else {
                    alert("Erro ao criar usuário");
                }
            },
            error: function () {
                alert("Erro ao criar usuário");
            }
        });
    })

    function init() {
        $("#CPF").mask('000.000.000-00', { reverse: true, placeholder: '000.000.000-00'});
    };

    $(function () { // DOM carregado
        init();
    });
</script>

Winmed/Views/Usuarios/Index.cshtml
@model IEnumerable<Winmed.Models.Usuario>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}
<link href="@Url.Content("~/Content/Usuario/CSS/usuario.min.css")" rel="stylesheet" />
<link href="@Url.Content("~/node_modules/bootstrap-table/src/bootstrap-table.css")" rel="stylesheet" />
<div class="container-user">
    <h4>Lista de usuários</h4>
    <table id="table"
           data-toggle="table"
           data-search="true"
           data-filter-control="true"
           data-show-export="true"
           data-click-to-select="false"
           data-toolbar="#toolbar">
        <thead>
            <tr>
                <th data-field="ID" data-filter-control="input" data-sortable="true">
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th data-field="Nome" data-filter-control="input" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th data-field="Sobrenome" data-filter-control="select" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Sobrenome)
                </th>
                <th data-field="Email" data-filter-control="select" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th data-field="CPF" data-sortable="true">
                    @Html.DisplayNameFor(model => model.CPF)
                </th>
                <th data-field="Delete" data-sortable="true">
                    Remover
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td id="id">@Html.DisplayFor(modelItem => item.ID)</td>
                    <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                    <td>@Html.DisplayFor(modelItem => item.Sobrenome)</td>
                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                    <td>@Html.DisplayFor(modelItem => item.CPF)</td>
                    <td>
                        <button class='btn btn-danger remover-usuario' id="lista_usuarios">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <script>
        $(document.body).on('click', '.remover-usuario', function () {
            if (confirm("Tem certeza que deseja deletar o usuário?")) {

                var id = $(this).closest('tr').find('#id').html();
                var form = $('#__AjaxAntiForgeryForm');
                var token = $('input[name="__RequestVerificationToken"]', form).val();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete")',
                    data: {
                        __RequestVerificationToken: token,
                        id: id
                    },
                    dataType: "json",
                    success: function () {
                        alert('Usuário deletado com sucesso!');
                        $('#content-container').load('@Url.Action("Index","Usuarios")');
                    },
                    error: function () {
                        alert("Erro ao deletar usuário");
                    }
                });
            }
        })

    </script>
    <script src="@Url.Content("~/node_modules/bootstrap-table/dist/bootstrap-table.js")"></script>
    <script src="@Url.Content("~/node_modules/bootstrap-table/dist/locale/bootstrap-table-pt-BR.js")"></script>